version: '3'
services:
  apache1:
      build: ./apache1
      #image: docker_apache1
      #image: ${DOCKER_REGISTRY}/docker_apache1:latest
      tty: true
      expose:
         - 80

  apache2:
      build: ./apache2
      #image: docker_apache2
      #image: ${DOCKER_REGISTRY}/docker_apache2:latest
      tty: true
      expose:
         - 80

  nginx:
      build: ./nginx
      image: docker_nginx
      #image: ${DOCKER_REGISTRY}/docker_nginx:latest
      tty: true
      links:
          - apache1:apache1
          - apache2:apache2
      ports:
          - '0:80'


